version: '3'
services:
  webservertmpdemo:
    image: nginx:mainline-alpine
    container_name: webservertmpdemo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/letsencrypt
      - /usr/share/nginx/html
volumes:
  certbot-var:


