docker-up:
	docker-compose up -d

docker-down:
	docker-compose down

docker-build:
	docker-compose up --build -d

## устновка ssl   демо игра  	      меняем домен и емейл  и запускаем
#docker-make-ssl-demo:
#    docker run -it --rm -v init_https-certs:/etc/letsencrypt  --volumes-from webservertmp certbot/certbot certonly --webroot --webroot-path=/usr/share/nginx/html -d devbestlookmybet.tk -d www.devbestlookmybet.tk  --email  biryukwolf1@gmail.com  --agree-tos


